name: Sync Repository

on:
  schedule:
    # 每天凌晨 3 点自动同步
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: vnetgo/edt
          token: ${{ secrets.PAT }} # 使用 PAT 访问源仓库
          path: target

      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: yutian81/edgetunnel-cmliu
          token: ${{ secrets.PAT }} # 使用 PAT 访问源仓库
          path: source

      # 强制同步源仓库到目标仓库
      - name: Force sync from source to target
        run: |
          rsync -av --delete source/ target/ # 同步文件
          cd target
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Force sync with A/aa repository" || echo "No changes to commit"
          git push origin main --force # 强制推送
