name: Sync Repository

on:
  schedule:
    # 每天凌晨 3 点自动同步
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: vnetgo/edt
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target

      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: yutian81/edgetunnel-cmliu
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source

      - name: Sync changes from source to target
        run: |
          rsync -av --delete source/ target/
          cd target
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync with yutian81/edgetunnel-cmliu on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
