name: Sync Repository

on:
  schedule:
    # 每天凌晨 3 点自动同步
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 拉取目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: vnetgo/edt
          token: ${{ secrets.PAT }} # 使用 PAT 访问目标仓库
          path: target
          fetch-depth: 0 # 禁用浅克隆，拉取完整历史

      # 拉取源仓库
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: yutian81/edgetunnel-cmliu
          token: ${{ secrets.PAT }} # 使用 PAT 访问目标仓库
          path: source
          fetch-depth: 0 # 禁用浅克隆，拉取完整历史

      # 同步源仓库到目标仓库
      - name: Sync changes
        run: |
          cd target
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add source ../source
          git fetch source
          git merge source/main --allow-unrelated-histories
          git push origin main
